/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaRouteImport } from './routes/pa'
import { Route as HousingRouteImport } from './routes/housing'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const PaRoute = PaRouteImport.update({
  id: '/pa',
  path: '/pa',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingRoute = HousingRouteImport.update({
  id: '/housing',
  path: '/housing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directory': typeof DirectoryRoute
  '/emergency': typeof EmergencyRoute
  '/housing': typeof HousingRoute
  '/pa': typeof PaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directory': typeof DirectoryRoute
  '/emergency': typeof EmergencyRoute
  '/housing': typeof HousingRoute
  '/pa': typeof PaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directory': typeof DirectoryRoute
  '/emergency': typeof EmergencyRoute
  '/housing': typeof HousingRoute
  '/pa': typeof PaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/directory'
    | '/emergency'
    | '/housing'
    | '/pa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/directory' | '/emergency' | '/housing' | '/pa'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/directory'
    | '/emergency'
    | '/housing'
    | '/pa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DirectoryRoute: typeof DirectoryRoute
  EmergencyRoute: typeof EmergencyRoute
  HousingRoute: typeof HousingRoute
  PaRoute: typeof PaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pa': {
      id: '/pa'
      path: '/pa'
      fullPath: '/pa'
      preLoaderRoute: typeof PaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing': {
      id: '/housing'
      path: '/housing'
      fullPath: '/housing'
      preLoaderRoute: typeof HousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DirectoryRoute: DirectoryRoute,
  EmergencyRoute: EmergencyRoute,
  HousingRoute: HousingRoute,
  PaRoute: PaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
