/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityForcesRouteImport } from './routes/security-forces'
import { Route as PaRouteImport } from './routes/pa'
import { Route as MedicalGroupRouteImport } from './routes/medical-group'
import { Route as LrsRouteImport } from './routes/lrs'
import { Route as HousingRouteImport } from './routes/housing'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const SecurityForcesRoute = SecurityForcesRouteImport.update({
  id: '/security-forces',
  path: '/security-forces',
  getParentRoute: () => rootRouteImport,
} as any)
const PaRoute = PaRouteImport.update({
  id: '/pa',
  path: '/pa',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalGroupRoute = MedicalGroupRouteImport.update({
  id: '/medical-group',
  path: '/medical-group',
  getParentRoute: () => rootRouteImport,
} as any)
const LrsRoute = LrsRouteImport.update({
  id: '/lrs',
  path: '/lrs',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingRoute = HousingRouteImport.update({
  id: '/housing',
  path: '/housing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directory': typeof DirectoryRoute
  '/emergency': typeof EmergencyRoute
  '/housing': typeof HousingRoute
  '/lrs': typeof LrsRoute
  '/medical-group': typeof MedicalGroupRoute
  '/pa': typeof PaRoute
  '/security-forces': typeof SecurityForcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directory': typeof DirectoryRoute
  '/emergency': typeof EmergencyRoute
  '/housing': typeof HousingRoute
  '/lrs': typeof LrsRoute
  '/medical-group': typeof MedicalGroupRoute
  '/pa': typeof PaRoute
  '/security-forces': typeof SecurityForcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directory': typeof DirectoryRoute
  '/emergency': typeof EmergencyRoute
  '/housing': typeof HousingRoute
  '/lrs': typeof LrsRoute
  '/medical-group': typeof MedicalGroupRoute
  '/pa': typeof PaRoute
  '/security-forces': typeof SecurityForcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/directory'
    | '/emergency'
    | '/housing'
    | '/lrs'
    | '/medical-group'
    | '/pa'
    | '/security-forces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/directory'
    | '/emergency'
    | '/housing'
    | '/lrs'
    | '/medical-group'
    | '/pa'
    | '/security-forces'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/directory'
    | '/emergency'
    | '/housing'
    | '/lrs'
    | '/medical-group'
    | '/pa'
    | '/security-forces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DirectoryRoute: typeof DirectoryRoute
  EmergencyRoute: typeof EmergencyRoute
  HousingRoute: typeof HousingRoute
  LrsRoute: typeof LrsRoute
  MedicalGroupRoute: typeof MedicalGroupRoute
  PaRoute: typeof PaRoute
  SecurityForcesRoute: typeof SecurityForcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security-forces': {
      id: '/security-forces'
      path: '/security-forces'
      fullPath: '/security-forces'
      preLoaderRoute: typeof SecurityForcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pa': {
      id: '/pa'
      path: '/pa'
      fullPath: '/pa'
      preLoaderRoute: typeof PaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-group': {
      id: '/medical-group'
      path: '/medical-group'
      fullPath: '/medical-group'
      preLoaderRoute: typeof MedicalGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lrs': {
      id: '/lrs'
      path: '/lrs'
      fullPath: '/lrs'
      preLoaderRoute: typeof LrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing': {
      id: '/housing'
      path: '/housing'
      fullPath: '/housing'
      preLoaderRoute: typeof HousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DirectoryRoute: DirectoryRoute,
  EmergencyRoute: EmergencyRoute,
  HousingRoute: HousingRoute,
  LrsRoute: LrsRoute,
  MedicalGroupRoute: MedicalGroupRoute,
  PaRoute: PaRoute,
  SecurityForcesRoute: SecurityForcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
